version: "3.9"

services:
  database:
    image: "postgres:12"
    container_name: "postgres12"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"
    volumes:
      - ./data:/var/lib/postgresql/data/
      - ./backup:/work/backup/
