version: "3.9"

services:
  database:
    image: "mysql:8.0"
    container_name: "mysql8"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "password"
      SERVICE_TAGS: "dev"
      SERVICE_NAME: "mysql"
    volumes:
      - ./data:/etc/mysql
      - ./backup:/work/backup/
